//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Doctor
    {
        public int DoctorID { get; set; }
        public string Tckn { get; set; }
        public string DoctorPassword { get; set; }
        public string DoctorName { get; set; }
        public string DoctorSurname { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public int HospitalID { get; set; }
        public Nullable<int> DoctorPopNo { get; set; }
    }
}
