//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient
    {
        public int PatientID { get; set; }
        public string Tckn { get; set; }
        public string PatientPassword { get; set; }
        public string PaitentName { get; set; }
        public string PaitentSurname { get; set; }
        public string PaitentMail { get; set; }
    }
}
