//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hour
    {
        public int HourID { get; set; }
        public System.TimeSpan Hour { get; set; }
        public int DateID { get; set; }
        public bool Active { get; set; }
    
        public virtual tbl_Date tbl_Date { get; set; }
    }
}
